
exports.REGISTER_USER_FIELDNAME_USERNAME = "username";
exports.REGISTER_USER_FIELDNAME_PRIVATE_KEY = "privateKey";
exports.REGISTER_USER_FIELDNAME_PUBLIC_KEY = "publicKey";
exports.REGISTER_USER_FIELDNAME_PASSWORD = "key_password";

exports.DATABASE_NAME = "pgpchat";
exports.DATABASE_USER_NAME = "pgpchatuser";
exports.DATABASE_USER_PASSWORD = "pgpchatuserpw";

exports.DATABASE_TABLE_USERS_NAME = "users";
exports.DATABASE_TABLE_USERS_NAME_MAXLEN = 30;

exports.DATABASE_TABLE_SESSIONS_SESSIONID_MAXLEN = 49;
